### ISSUE TITLE
Could not build url for endpoint 'event.view_event' with values ['id']

### ISSUE THREAD

**Issue by jnguiot** [Club-Alpin-Annecy/collectives-flask2#17]
Suite au merge de la PR 14 https://github.com/Club-Alpin-Annecy/collectives-flask2/pull/14, on a cette erreur sur /event/X et /event/index.
```werkzeug.routing.BuildError

werkzeug.routing.BuildError: Could not build url for endpoint 'event.view_event' with values ['id']. Did you forget to specify values ['event_id']?
Traceback (most recent call last)

    File "C:\Program Files (x86)\Python38-32\Lib\site-packages\flask\app.py", line 2463, in __call__

    return self.wsgi_app(environ, start_response)

    File "C:\Program Files (x86)\Python38-32\Lib\site-packages\flask\app.py", line 2449, in wsgi_app

    response = self.handle_exception(e)

    File "C:\Program Files (x86)\Python38-32\Lib\site-packages\flask\app.py", line 1866, in handle_exception

    reraise(exc_type, exc_value, tb)

    File "C:\Program Files (x86)\Python38-32\Lib\site-packages\flask\_compat.py", line 39, in reraise

    raise value

    File "C:\Program Files (x86)\Python38-32\Lib\site-packages\flask\app.py", line 2446, in wsgi_app

    response = self.full_dispatch_request()

    File "C:\Program Files (x86)\Python38-32\Lib\site-packages\flask\app.py", line 1951, in full_dispatch_request

    rv = self.handle_user_exception(e)

    File "C:\Program Files (x86)\Python38-32\Lib\site-packages\flask\app.py", line 1820, in handle_user_exception

    reraise(exc_type, exc_value, tb)

    File "C:\Program Files (x86)\Python38-32\Lib\site-packages\flask\_compat.py", line 39, in reraise

    raise value

    File "C:\Program Files (x86)\Python38-32\Lib\site-packages\flask\app.py", line 1949, in full_dispatch_request

    rv = self.dispatch_request()

    File "C:\Program Files (x86)\Python38-32\Lib\site-packages\flask\app.py", line 1935, in dispatch_request

    return self.view_functions[rule.endpoint](**req.view_args)

    File "H:\8172\collectives\event.py", line 24, in index

    return render_template('index.html',

    File "C:\Program Files (x86)\Python38-32\Lib\site-packages\flask\templating.py", line 137, in render_template

    return _render(

    File "C:\Program Files (x86)\Python38-32\Lib\site-packages\flask\templating.py", line 120, in _render

    rv = template.render(context)

    File "C:\Program Files (x86)\Python38-32\Lib\site-packages\jinja2\asyncsupport.py", line 76, in render

    return original_render(self, *args, **kwargs)

    File "C:\Program Files (x86)\Python38-32\Lib\site-packages\jinja2\environment.py", line 1008, in render

    return self.environment.handle_exception(exc_info, True)

    File "C:\Program Files (x86)\Python38-32\Lib\site-packages\jinja2\environment.py", line 780, in handle_exception

    reraise(exc_type, exc_value, tb)

    File "C:\Program Files (x86)\Python38-32\Lib\site-packages\jinja2\_compat.py", line 37, in reraise

    raise value.with_traceback(tb)

    File "H:\8172\collectives\templates\index.html", line 4, in <module>

    {% import 'macros.html' as macros with context %}

    File "C:\Program Files (x86)\Python38-32\Lib\site-packages\jinja2\environment.py", line 1005, in render

    return concat(self.root_render_func(self.new_context(vars)))

    File "H:\8172\collectives\templates\index.html", line 19, in root

    {% endfor %}

    File "H:\8172\collectives\templates\base.html", line 85, in root

    {% block content %}{% endblock %}

    File "H:\8172\collectives\templates\index.html", line 58, in block_content

     

    File "C:\Program Files (x86)\Python38-32\Lib\site-packages\jinja2\runtime.py", line 570, in __call__

    return self._invoke(arguments, autoescape)

    File "C:\Program Files (x86)\Python38-32\Lib\site-packages\jinja2\asyncsupport.py", line 110, in _invoke

    return original_invoke(self, arguments, autoescape)

    File "C:\Program Files (x86)\Python38-32\Lib\site-packages\jinja2\runtime.py", line 574, in _invoke

    rv = self._func(*arguments)

    File "H:\8172\collectives\templates\macros.html", line 83, in macro

     

    File "C:\Program Files (x86)\Python38-32\Lib\site-packages\flask\helpers.py", line 370, in url_for

    return appctx.app.handle_url_build_error(error, endpoint, values)

    File "C:\Program Files (x86)\Python38-32\Lib\site-packages\flask\app.py", line 2215, in handle_url_build_error

    reraise(exc_type, exc_value, tb)

    File "C:\Program Files (x86)\Python38-32\Lib\site-packages\flask\_compat.py", line 39, in reraise

    raise value

    File "C:\Program Files (x86)\Python38-32\Lib\site-packages\flask\helpers.py", line 357, in url_for

    rv = url_adapter.build(

    File "C:\Program Files (x86)\Python38-32\Lib\site-packages\werkzeug\routing.py", line 2020, in build

    raise BuildError(endpoint, values, method, self)

    werkzeug.routing.BuildError: Could not build url for endpoint 'event.view_event' with values ['id']. Did you forget to specify values ['event_id']?

```

**Comment by jnguiot** [comment]
Fixé dans le commit  6083cf1
